name: "Create changelog"
description: "Generates a changelog from a Git repository commit history."
author: "Arduino"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "list"
  color: "blue"
